use_frameworks!

platform :ios, '11.0'

target 'HYVideoSDK_Example' do
  
#  post_install do |installer|
#    installer.pods_project.targets.each do |target|
#      target.build_configurations.each do |config|
#        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
#      end
#    end
#  end

  use_frameworks!

  pod 'HYVideoSDK', :path => '../'

#  pod 'HYVideoDB',:git =>"https://github.com/huboceanLi/HYVideoDB.git"

  target 'HYVideoSDK_Tests' do
    inherit! :search_paths

    
  end
end

