use_frameworks!

platform :ios, '10.0'

target 'HYVideoSDK_Example' do
  pod 'HYVideoSDK', :path => '../'
  pod 'HYBaseTool', '1.0.1'

  target 'HYVideoSDK_Tests' do
    inherit! :search_paths

    
  end
end
